# aws
aws:
  region: ap-southeast-1
  accessKeyId:
  secretAccessKey:
  sessionToken:
  s3:
    bucket: test
    presignedGetUrlDuration: 5
    presignedPutUrlDuration: 20

# database
database:
  url: "postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-password}@${DB_HOST:-localhost}:${DB_PORT:-5432}/${DB_NAME:-cubone}?${DB_PARAMS:-schema=public&connection_limit=5&pool_timeout=0}"

# security
security:
  authentication:
    jwksUri: "https://cognito-idp.ap-southeast-1.amazonaws.com/ap-southeast-1_3Akef3YUb/.well-known/jwks.json"

# http clients
httpClients:
  - url: "http://localhost:8080"
  - url: "http://localhost:8081"